[build.targets.wheel]
packages = ["unit_standardizer"]
include = [
    "unit_standardizer"
]
exclude = [
    "**/tests",
    "**/test_*.py",
]

[build.targets.sdist]
packages = ["unit_standardizer"]
include = [
    "unit_standardizer"
]
exclude = [
    "**/tests",
    "**/test_*.py",
]
