name: MyPy

on:
  pull_request:
    branches:
      - main

jobs:
  mypy:
    concurrency:
      group: mypy-${{ github.event_name}}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    container:
      image: python:3.13
    steps:
      - uses: actions/checkout@v5
      
      - name: Install MyPy
        run: pip install mypy

      - name: Run MyPy
        run: mypy .
